DROP table ACCOUNT_DETAILS;
DROP table CUSTOMER;
DROP table TRANSACTION_DETAILS;


CREATE TABLE ACCOUNT_DETAILS
  (
    ACCOUNT_HOLDER_NAME VARCHAR2(20 BYTE),
    ACCOUNT_NUMBER      NUMBER,
    ACCOUNT_TYPE        VARCHAR2(20 BYTE),
    ACCOUNT_DETAILS     VARCHAR2(20 BYTE),
    BALANCE            NUMBER
  )
  
  CREATE TABLE CUSTOMER
  (
    USERNAME      VARCHAR2(20 BYTE),
    PASSWORD      VARCHAR2(20 BYTE),
    SEC_QUESTION  VARCHAR2(50 BYTE),
    ANSWER        VARCHAR2(20 BYTE),
    ADDRESS       VARCHAR2(50 BYTE),
    EMAIL_ADDRESS  VARCHAR2(30 BYTE),
    MOBILE_NUMBER  VARCHAR2(10 BYTE)
  )
  
  CREATE TABLE TRANSACTION_DETAILS
  (
    ACCOUNT_HOLDER_NAME   VARCHAR2(20 BYTE),
    SOURCE_ACCOUNT_NUMBER NUMBER(10,0),
    DEST_ACCOUNT_NUMBER   NUMBER,
    OPERATION             VARCHAR2(20 BYTE),
    AMOUNT                NUMBER,
    TRANSACTION_TIME      DATE
  )